_BASE_: [
  '../../../configs/dfine/dfine_hgnetv2_l_coco.yml',
  '_base_/deim_dfine.yml',
]

save_dir: output/deim_hgnetv2_l_coco
epoch: 58
base_lr: 0.0005
ema_restart_decay: 0.9999

TrainingProtocol:
  name: TwoStageDetectionProtocol
  family: deim
  stop_epoch: 50
  ema_restart_decay: 0.9999

LearningRate:
  base_lr: 0.0005
  schedulers:
    - name: FlatCosineLRScheduler
      total_epochs: 58
      warmup_iter: 2000
      flat_epochs: 29
      no_aug_epochs: 8
      lr_gamma: 0.5

OptimizerBuilder:
  optimizer:
    weight_decay: 0.000125
    param_groups:
      - params: ['^backbone\.(?!.*(?:norm|bn)).*$']
        lr: 0.000025
      - params: ['^(?:encoder|decoder)\..*(?:norm|bn).*$']
        weight_decay: 0.0

TrainReader:
  total_batch_size: 32
  dense_o2o_policy:
    policy_epochs: [4, 29, 50]
    mixup_epochs: [4, 29]
    multiscale_stop_epoch: 50
    multiscale_sizes: [480, 512, 544, 576, 608, 640, 640, 640, 640, 672, 704, 736, 768, 800]
