# RT-DETRv3 ResNet-50 VD 6x COCO Configuration

# Model Configuration
model:
  type: RTDETRv3_R50
  num_classes: 80
  aux_loss: true
  backbone:
    type: ResNetVD
    depth: 50
    return_idx: [1, 2, 3]
    norm_type: bn
    freeze_at: -1
  neck:
    type: HybridEncoder
    in_channels: [512, 1024, 2048]
    feat_strides: [8, 16, 32]
    hidden_dim: 256
    use_encoder_idx: [2]
    num_encoder_layers: 1
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.0
    activation: silu
  transformer:
    type: RTDETRTransformerV3
    num_classes: 80
    hidden_dim: 256
    num_queries: 300
    num_decoder_layers: 6
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.0
    activation: relu
    num_denoising: 100
    label_noise_ratio: 0.5
    box_noise_scale: 1.0
    learnt_init_query: true
  head:
    type: RTDETRHead
    num_classes: 80
    hidden_dim: 256
    num_queries: 300
    num_decoder_layers: 6
    aux_loss: true
  post_processor:
    type: RTDETRPostProcessor
    num_classes: 80
    num_queries: 300
    use_focal_loss: true
    use_nms: false
    score_threshold: 0.0
    max_detections: 300

# Loss Configuration
criterion:
  type: RTDETRCriterion
  num_classes: 80
  matcher:
    type: HungarianMatcher
    cost_class: 1.0
    cost_bbox: 5.0
    cost_giou: 2.0
  weight_dict:
    loss_ce: 1.0
    loss_bbox: 5.0
    loss_giou: 2.0
  losses: ['labels', 'boxes', 'cardinality']
  focal_alpha: 0.25
  focal_gamma: 2.0
  aux_loss: true

# Training Configuration
train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDataset
    image_dir: train2017
    ann_file: annotations/instances_train2017.json
    transforms:
      - type: RandomResize
        sizes: [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
        max_size: 1333
      - type: RandomHorizontalFlip
        prob: 0.5
      - type: ToTensor
      - type: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  batch_size: 2
  shuffle: true
  num_workers: 4
  pin_memory: true
  drop_last: true

# Validation Configuration
val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDataset
    image_dir: val2017
    ann_file: annotations/instances_val2017.json
    transforms:
      - type: Resize
        size: 640
      - type: ToTensor
      - type: Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  batch_size: 2
  shuffle: false
  num_workers: 4
  pin_memory: true
  drop_last: false

# Optimizer Configuration
optimizer:
  type: AdamW
  lr: 0.0001
  weight_decay: 0.0001
  params:
    - params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - params: '^(?=.*norm).*$'
      weight_decay: 0.0

# Learning Rate Scheduler
lr_scheduler:
  type: MultiStepLR
  milestones: [40, 60]
  gamma: 0.1

# Training Settings
epoches: 72
use_amp: false
use_ema: false
clip_max_norm: 0.1
find_unused_parameters: false
sync_bn: false

# Evaluation Settings
evaluator:
  type: CocoEvaluator

# Runtime Settings
print_freq: 50
checkpoint_freq: 10
output_dir: "./outputs/rtdetrv3_r50vd_6x_coco"
device: "cuda"
seed: 42